### ISSUE TITLE
NameError: name 'options' is not defined

### ISSUE THREAD

**Issue by 0MazaHacka0** [secretsquirrel/BDFProxy#49]
i installed mitmproxy 0.14 and now i get
Traceback (most recent call last):
File "./bdf_proxy.py", line 821, in
config = proxy.ProxyConfig(options.Options(clientcerts=os.path.expanduser(user_config['Overall']['certLocation']),
NameError: name 'options' is not defined

**Comment by secretsquirrel** [comment]
I don't know.

I can't replicate your issue.

**Comment by secretsquirrel** [comment]
Also see: https://github.com/secretsquirrel/BDFProxy/blob/master/README.md#bug-reporting

**Comment by kalzoo** [comment]
I'm getting this error as well. Writing it here instead of bugreporting for more visibility.
I have attempted to get bdfproxy working with every version of mitmproxy in that range, and all fail, with unique errors for each. 

Most appear to be caused by the try/except block in bdf_proxy.py: 30-36
mitm 0.11 -> 
~~~~
Traceback (most recent call last):
  File "./bdf_proxy.py", line 821, in <module>
    config = proxy.ProxyConfig(options.Options(clientcerts=os.path.expanduser(user_config['Overall']['certLocation']),
NameError: name 'options' is not defined
~~~~

0.12 -> 
mitmproxy install fails:
~~~~
"Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-YHazaL/netlib/"
~~~~

0.13 ->
~~~~
  File "./bdf_proxy.py", line 34, in <module>
    from libmproxy import controller, proxy, platform
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/proxy/__init__.py", line 1, in <module>
    from .primitives import *
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/proxy/primitives.py", line 2, in <module>
    from netlib import socks, tcp
ImportError: No module named netlib
~~~~

0.14 -> as above.

0.15-0.17 -> mitmproxy install fails (`failed to build wheel for cryptography`). working on that one - pip, libssldev, etc, etc, are all updated.

In any case, the root of the issue seems to be that bdf_proxy.py assumes mitmproxy 0.17 is installed. prior to 0.17, per the mitmproxy release notes, it was named libmproxy, which is what is included in bdf_proxy.py if mitmproxy is not present. However, libmproxy has no component "options," and so throws an error around line 821, when options is called but does not exist.

**Comment by kalzoo** [comment]
[Solved] As followup:
Inputs - Kali 2017.1, pip, python 2.7, bdfproxy all updated. 

`pip install mitmproxy=0.xx` fails for every version 0.11-0.17 except for 0.14 for me - issues with dependencies `cryptography` and `lxml`. Of course, that's a `mitmproxy` issue not `bdfproxy`, but it's `bdfproxy` that limits us to those problematic `mitmproxy` versions. A current `mitmproxy` installation works great but crashes `bdfproxy`.

Issues resolved:
1. `apt-get install bdfproxy` does not appear to pull from the correct repo or version. The `/usr/share/bdf_proxy.py` is not identical to the most recent version on this repo, whether installed with `apt-get` or a `git clone` followed by `install.py`. I don't know why. **Fix:** clone this repo, or just save the `bdf_proxy.py` file, and replace it into the `/usr/share/bdfproxy` directory. Of course, backup the original first.

2.  After that, `bdfproxy` will throw a new error: `ImportError: no module named netlib`. However, a `pip freeze` shows that `netlib` is installed (0.14). **Fix:** you have to uninstall that `mitmproxy` dependencies and reinstall:
~~~~
pip uninstall mitmproxy
pip uninstall netlib
pip uninstall pathod
pip install mitmproxy==0.14

bdfproxy
~~~~

That should fix this issue. Good luck

**Comment by secretsquirrel** [comment]
Congrats!
